### ISSUE TITLE
Can't working with `Debug JS Remotely` Together on android, ios is fine

### ISSUE THREAD

**Issue by feyy** [jhen0409/remotedev-rn-debugger#14]
When not `Debug JS Remotely`, the log monitor works fine. But after click `Debug JS Remotely`, the log monitor didn't log anything. Logs below:
![image](https://cloud.githubusercontent.com/assets/3056002/17846632/434492fa-687c-11e6-913c-35be43256d90.png)

**Comment by zalmoxisus** [comment]
@feyy, when you restart the app from android emulator, do you get [this error](https://github.com/zalmoxisus/remote-redux-devtools/issues/4) there? Do you use a local server?

**Comment by jhen0409** [comment]
I can reproduce the problem, but only on RN v0.31 with debug mode, maybe it just related to WebSocket (React inspector of [RNDebugger](https://github.com/jhen0409/react-native-debugger) also not work).

**Comment by feyy** [comment]
Thanks very much! I just use v0.31.
