### ISSUE TITLE
Rename to `remotedev-on-debugger`

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/remotedev-rn-debugger#18]
We can use this module for [`remotedev`](https://github.com/zalmoxisus/remotedev) and [`mobx-remotedev`](https://github.com/zalmoxisus/mobx-remotedev), `remotedev-on-debugger` will be better name.

**Comment by zalmoxisus** [comment]
👍 

Moreover that the plans are to support non-redux monitors in `remotedev-app`.

It also could be `remotedev-on-react-native-debugger`, but I guess it's too long.

**Comment by jhen0409** [comment]
I decided to call it `remotedev-rn-debugger`, it will be shorter and clear.

**Comment by zalmoxisus** [comment]
Sounds good 👍
