### ISSUE TITLE
failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by easadler** [jhen0409/remotedev-rn-debugger#19]
Any ideas for why I would be getting this error? 
![screen shot 2017-02-05 at 8 37 27 pm](https://cloud.githubusercontent.com/assets/7134016/22632943/f9f8fd76-ebe2-11e6-995f-097c4595279f.png)

The debugger shows up on the debugger-ui, but it clearly isn't connecting to the local host. I am using Exponent and the port is on 19001, which I am manually setting. Here is what I currently have:

```
"scripts": {
    "test": "jest",
    "postinstall": "remotedev-debugger --hostname localhost --port 19001"
  }
```

```
const enhancer = compose(
    devTools({
      name: Platform.OS,
      hostname: 'localhost',
      port: 19001
    })
  );
```
I've gotten it to work with remote-redux-devtools by itself so I know it isn't that.

**Comment by jhen0409** [comment]
@easadler It has server options but I can't see the `--injectserver` or `--runserver` usage, have you a running `remotedev-server` but still experiencing this problem?

**Comment by zalmoxisus** [comment]
You shouldn't use the same port as for Exponent here.
